version: '3.1'

services:

  postgres:
    image: postgres:12
    container_name: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: movie_library
    ports:
      - 5432:5432
    networks:
      - app_network

  movie_library:
    build:
      context: ./
    image: movie_library:latest
    container_name: movie_library
    ports:
      - 8000:8000
    environment:
      HOST: 0.0.0.0
      PORT: 8000
      NODE_ENV: development
      APP_KEY: zpn2r9oD196wDqvW3rEYPVPgEhX0YVYF
      DB_CONNECTION: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: movie_library
      OMDB_API_KEY: 5efec7ec
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_volume:
